import { describe, expect, it } from 'vitest'

import { hashPassword, verifyPassword } from '../password'

describe('password hashing', () => {
  it('uses Cloudflare-worker-safe PBKDF2 iterations', async () => {
    const hashed = await hashPassword('secret_password_123')
    const [, iterations] = hashed.split('$')
    expect(iterations).toBe('100000')
  })

  it('verifies a password generated by hashPassword', async () => {
    const password = 'secret_password_123'
    const hashed = await hashPassword(password)
    await expect(verifyPassword(password, hashed)).resolves.toBe(true)
    await expect(verifyPassword('wrong_password', hashed)).resolves.toBe(false)
  })
})
